# Generated by Django 5.2.5 on 2026-03-31 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Load Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('pickup_city', models.CharField(max_length=100, verbose_name='Pickup City')),
                ('pickup_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pickup Address')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Delivery City')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Address')),
                ('pickup_date', models.DateField(verbose_name='Pickup Date')),
                ('pickup_time', models.TimeField(blank=True, null=True, verbose_name='Pickup Time')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('delivery_time', models.TimeField(blank=True, null=True, verbose_name='Delivery Time')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Weight (tons)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Volume (m³)')),
                ('cargo_type', models.CharField(choices=[('general', 'General Cargo'), ('pallet', 'Pallets'), ('refrigerator', 'Refrigerated'), ('oversize', 'Oversize'), ('hazardous', 'Hazardous'), ('livestock', 'Livestock'), ('vehicles', 'Vehicles')], max_length=20, verbose_name='Cargo Type')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Length (m)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Width (m)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Height (m)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Offered Price')),
                ('price_negotiable', models.BooleanField(default=True, verbose_name='Price Negotiable')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reserved', 'Reserved'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=15, verbose_name='Status')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('contact_count', models.PositiveIntegerField(default=0, verbose_name='Contacts Received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expires At')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargoes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('cargo', 'Cargo'), ('transport', 'Transport')], max_length=10)),
                ('listing_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('fraud', 'Fraud / Scam'), ('inappropriate', 'Inappropriate Content'), ('duplicate', 'Duplicate Listing'), ('expired', 'Expired'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing Report',
                'verbose_name_plural': 'Listing Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Vehicle Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('available_city_from', models.CharField(max_length=100, verbose_name='Available From City')),
                ('available_city_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Available To City')),
                ('current_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Location')),
                ('available_from_date', models.DateField(verbose_name='Available From Date')),
                ('available_from_time', models.TimeField(blank=True, null=True, verbose_name='Available From Time')),
                ('available_to_date', models.DateField(blank=True, null=True, verbose_name='Available To Date')),
                ('available_to_time', models.TimeField(blank=True, null=True, verbose_name='Available To Time')),
                ('transport_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('refrigerator', 'Refrigerator Truck'), ('oversize', 'Oversize Transport'), ('trailer', 'Trailer'), ('container', 'Container'), ('tanker', 'Tanker')], max_length=20, verbose_name='Vehicle Type')),
                ('capacity_weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacity (tons)')),
                ('capacity_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacity (m³)')),
                ('truck_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Truck Model')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='License Plate')),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price per km')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixed Price')),
                ('price_negotiable', models.BooleanField(default=True, verbose_name='Price Negotiable')),
                ('has_gps', models.BooleanField(default=False, verbose_name='GPS Tracking')),
                ('has_driver', models.BooleanField(default=True, verbose_name='Driver Included')),
                ('has_temperature_control', models.BooleanField(default=False, verbose_name='Temperature Control')),
                ('insurance_included', models.BooleanField(default=False, verbose_name='Insurance Included')),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('in_transit', 'In Transit'), ('unavailable', 'Unavailable')], default='available', max_length=15, verbose_name='Status')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('contact_count', models.PositiveIntegerField(default=0, verbose_name='Contacts Received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expires At')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Message Content')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_deleted_by_sender', models.BooleanField(default=False)),
                ('is_deleted_by_receiver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.cargo')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.transport')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['pickup_city', 'delivery_city'], name='core_cargo_pickup__f4b53e_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['pickup_date'], name='core_cargo_pickup__43c1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['status'], name='core_cargo_status_a04765_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['cargo_type'], name='core_cargo_cargo_t_94d2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['available_city_from'], name='core_transp_availab_8efe15_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['available_from_date'], name='core_transp_availab_276483_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['status'], name='core_transp_status_cd20b2_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['transport_type'], name='core_transp_transpo_f88c57_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver'], name='core_messag_sender__2a6008_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='core_messag_is_read_b327c3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='core_messag_created_a655d0_idx'),
        ),
    ]
