# Generated by Django 5.2.5 on 2026-04-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Status Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Status Code')),
                ('color', models.CharField(default='gray', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Cargo Status',
                'verbose_name_plural': 'Cargo Statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Type Code')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Cargo Type',
                'verbose_name_plural': 'Cargo Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Status Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Status Code')),
                ('color', models.CharField(default='gray', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Transport Status',
                'verbose_name_plural': 'Transport Statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Type Code')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Transport Type',
                'verbose_name_plural': 'Transport Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='cargo',
            new_name='core_cargo_status__431c76_idx',
            old_name='core_cargo_status_a04765_idx',
        ),
        migrations.RenameIndex(
            model_name='cargo',
            new_name='core_cargo_cargo_t_deed54_idx',
            old_name='core_cargo_cargo_t_94d2fd_idx',
        ),
        migrations.RenameIndex(
            model_name='transport',
            new_name='core_transp_status__311115_idx',
            old_name='core_transp_status_cd20b2_idx',
        ),
        migrations.RenameIndex(
            model_name='transport',
            new_name='core_transp_transpo_f7b686_idx',
            old_name='core_transp_transpo_f88c57_idx',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cargoes', to='core.cargostatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargoes', to='core.cargotype', verbose_name='Cargo Type'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='core.transportstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='core.transporttype', verbose_name='Vehicle Type'),
        ),
    ]
