# Generated by Django 5.2.5 on 2026-03-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('shipper', 'Shipper'), ('carrier', 'Carrier'), ('admin', 'Admin')], default='shipper', max_length=20),
        ),
    ]
